# https://docs.codeclimate.com/docs/advanced-configuration
version: "2"         # required to adjust maintainability checks
checks:
  file-lines:
    config:
      threshold: 1000
  return-statements:
    config:
      threshold: 10
  method-complexity:
    config:
      threshold: 6
plugins:
  bandit:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - selftests/**
exclude_patterns:
  - selftests/**
  - setup.py
